name: Build PDF

on:
  push:
    paths:
      - '**.tex'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: LADR4e-Alternative-Solutions.tex
          latexmk_use_xelatex: false

      - name: Update latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest PDF
          files: LADR4e-Alternative-Solutions.pdf
          make_latest: true